{"name": "test_login_user_by_wrong_name", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400", "trace": "self = <test_api.TestWrongParameters object at 0x000001599AE8DF40>, add_one_user = <api_connector.ApiConnector object at 0x000001599AF72280>\n\n    @allure.feature(\"Login user into the system  /user/login\")\n    @allure.story('Выполняем вход пользователя с некорректным username')\n    @pytest.mark.login_user\n    def test_login_user_by_wrong_name(self, add_one_user):\n        \"\"\"logged user by wrong name and correct password\"\"\"\n        name = 'test1'\n        password = '12345'\n        with allure.step(f\"Выполняем вход пользователя username={name}, password={password}\"):\n            rez = add_one_user.login_user(name=name, password=password)\n        with allure.step(f\"Запрос отправлен, проверяем код ответа {rez[0]} == 400\"):\n>           assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 400\n\ntest_api.py:291: AssertionError"}, "description": "logged user by wrong name and correct password", "steps": [{"name": "Выполняем вход пользователя username=test1, password=12345", "status": "passed", "steps": [{"name": "get request to: https://petstore.swagger.io/v2/user/login", "status": "passed", "start": 1661756092147, "stop": 1661756092147}], "start": 1661756091440, "stop": 1661756092147}, {"name": "Запрос отправлен, проверяем код ответа 200 == 400", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 291, in test_login_user_by_wrong_name\n    assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661756092147, "stop": 1661756092147}], "attachments": [{"name": "log", "source": "59c3b069-ce39-4b11-8309-927ca0d97b05-attachment.txt", "type": "text/plain"}], "start": 1661756091440, "stop": 1661756092148, "uuid": "ac98c905-59a7-404d-b36e-7d1ab7d48c1b", "historyId": "4f35d294161835c489a293a31e22869d", "testCaseId": "4c1d4e8712721e3395bdd7c94e567bbc", "fullName": "test_api.TestWrongParameters#test_login_user_by_wrong_name", "labels": [{"name": "feature", "value": "Login user into the system  /user/login"}, {"name": "story", "value": "Выполняем вход пользователя с некорректным username"}, {"name": "tag", "value": "login_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "8876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}